### PR TITLE
Initial

### PR DESCRIPTION
**Pull request by Rock0007**
De SchoolMate

### CODE REVIEW

**Comment by SpandanM110** [comment]
Dude I say if you made it fully workable I will be merging it fully and finally.

**Comment by Rock0007** [comment]
I will transform the project fully into vite later, merge this for now since hacktober-fest is ending. I will do update it for sure. I hope you have seen the preview of my work. I have enhanced the home page in 3 hrs.

**Comment by Rock0007** [comment]
@SpandanM110 ^^

**Comment by SpandanM110** [comment]
We are merging it in vite branch and when the work is done fully we will merge it in Main branch hope it works for you. @Rock0007

**Comment by srummanf** [comment]
Yes I agree with @SpandanM110

**Comment by Rock0007** [comment]
> We are merging it in vite branch and when the work is done fully we will merge it in Main branch hope it works for you. @Rock0007

Yeah sure, I will start my work tomorrow @SpandanM110

**Pull request merged**
