### PR TITLE
Fixed opening in other tab isssue.

### PR DESCRIPTION
**Pull request by Dushyant-Mahto**
* Fixes issue number #43

### CODE REVIEW

**Comment by SpandanM110** [comment]
@Dushyant-Mahto Dude when we click on Open App it is going smoothly but when we return using the home button it is showing in new tab 

You can make changes overall in as many PRs you want make sure the bug is solved fully even in app there is the same problem.

**Comment by Dushyant-Mahto** [comment]
Yeah, I've rectified it now, please check

**Comment by SpandanM110** [comment]
Nice can you solve the issue for other application like todo list and all the home button opens to the new tab so can you solve it I am merging this PR don't worry.

**Comment by Dushyant-Mahto** [comment]
Sure, on it!

**Pull request merged**
